wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721881833
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.10.14
      5: 0.17.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
